import puppeteer from 'puppeteer-core'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import { verifySafariReveal } from './verify-safari-reveal.mjs'

const origin = process.env.SAFARI_TEST_ORIGIN || 'http://localhost:8790'
const live = process.argv.includes('--live')
const sample = JSON.parse(await fs.readFile(new URL('../public/safari/example/workshop.json', import.meta.url), 'utf8'))
const output = path.resolve('output/safari-ui')
await fs.mkdir(path.join(output, 'downloads'), { recursive: true })
const browser = await puppeteer.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true })
const checks = [], errors = []
try {
  const page = await browser.newPage()
  await browser.defaultBrowserContext().overridePermissions(origin, ['clipboard-read', 'clipboard-write'])
  const cdp = await page.createCDPSession()
  await cdp.send('Page.setDownloadBehavior', { behavior: 'allow', downloadPath: path.join(output, 'downloads') })
  page.on('pageerror', error => errors.push(error.message))
  let mode = 'fixture', runs = 0
  await page.setRequestInterception(true)
  page.on('request', request => {
    if (!request.url().endsWith('/api/safari/run')) return request.continue()
    runs++
    if (mode === 'live') return request.continue()
    return request.abort('blockedbyclient')
  })
  const click = selector => page.locator(selector).click()
  const noOverflow = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `Horizontal overflow at ${page.viewport().width}px`)
  const finishMotion = () => page.evaluate(() => Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {}))))
  const shot = async (name, fullPage = false) => { await finishMotion(); await page.screenshot({ path: path.join(output, `${name}.png`), fullPage }) }
  const readFind = async () => { const title = await page.$eval('.sf-find-face h2', el => el.textContent); return sample.cards.find(c => c.title === title) }
  const close = () => page.keyboard.press('Escape')
  await page.setViewport({ width: 1440, height: 1000, deviceScaleFactor: 1 })
  await page.goto(`${origin}/safari/`, { waitUntil: 'networkidle0' })
  await page.waitForSelector('#sf-challenge')
  await page.evaluate(() => localStorage.setItem('safari-test-change-cards-sentinel', 'untouched'))
  await shot('landing-desktop')
  for (const width of [768, 390, 320]) {
    await page.setViewport({ width, height: 844 }); await noOverflow()
    assert.ok(await page.evaluate(() => {
      const copy = document.querySelector('.sf-intro').getBoundingClientRect()
      return [...document.querySelectorAll('.sf-fan-card')].every(el => { const art = el.getBoundingClientRect(); return art.left >= copy.right || art.top >= copy.bottom || art.bottom <= copy.top })
    }), `Decorative cards cover the introduction at ${width}px`)
  }
  await page.setViewport({ width: 390, height: 844 }); await shot('landing-mobile')
  assert.equal(runs, 0)
  await click('.sf-example')
  await page.waitForSelector('.sf-tabletop')
  assert.equal(await page.$$eval('.sf-pile', items => items.length), 6)
  assert.equal(runs, 0, 'Neither page load nor the example may generate evidence')
  for (const width of [1440, 768, 390, 320]) { await page.setViewport({ width, height: 1000 }); await noOverflow() }
  await page.setViewport({ width: 1440, height: 1000 })
  await page.waitForFunction(() => [...document.querySelectorAll('.sf-pile img')].every(img => img.complete && img.naturalWidth > 0))
  assert.equal(await page.$$eval('.sf-pile', els => new Set(els.map(el => getComputedStyle(el).backgroundColor)).size), 6)
  await shot('tabletop-desktop', true)
  await page.setViewport({ width: 390, height: 844 }); await shot('tabletop-mobile', true)
  await page.setViewport({ width: 1440, height: 1000 })
  await click('.sf-pile')
  await page.waitForSelector('.sf-find-dialog[open]')
  const first = await readFind()
  assert.ok(first)
  assert.equal(await page.$$eval('.sf-look-closer[open]', els => els.length), 0)
  assert.equal(await page.$eval('.sf-find-source a', a => a.href), sample.sources.find(s => s.id === first.sourceId).url)
  await shot('finding-desktop')
  await click('.sf-look-closer > summary')
  await click('.sf-source-detail > summary')
  assert.equal(await page.$eval('.sf-source-detail a', a => a.href), sample.sources.find(s => s.id === first.sourceId).url)
  await shot('finding-expanded')
  await click('.sf-keep-button')
  await click('.sf-detour-button')
  await page.waitForFunction(title => document.querySelector('.sf-find-face h2').textContent !== title, {}, first.title)
  const second = await readFind()
  assert.notEqual(second.lens, first.lens)
  assert.equal(await page.$('.sf-look-closer[open]'), null, 'A new discovery starts digestible again')
  await click('.sf-keep-button')
  for (const width of [768, 390, 320]) { await page.setViewport({ width, height: 844 }); await noOverflow() }
  await page.setViewport({ width: 390, height: 844 }); await shot('finding-mobile')
  await close()
  await click('.sf-guide-button')
  await page.waitForSelector('.sf-guide-dialog[open]')
  await page.type('.sf-reflection textarea', 'Free does not remove the cost of time.')
  const firstNote = await page.$('.sf-saved-list article textarea')
  await firstNote.type('Ask potential participants about workload.')
  await click('.sf-export-actions .sf-primary')
  await page.waitForSelector('dialog .sf-toast')
  const clipboard = await page.evaluate(() => navigator.clipboard.readText())
  for (const text of ['Free does not remove the cost of time.', 'Ask potential participants about workload.', '**Transfer caution:**', first.supportQuote, second.supportQuote]) assert.ok(clipboard.includes(text))
  const omitted = sample.cards.find(c => ![first.id, second.id].includes(c.id))
  assert.ok(!clipboard.includes(omitted.finding))
  await click('.sf-export-actions .sf-secondary')
  await shot('guide-mobile')
  await page.setViewport({ width: 1440, height: 1000 }); await shot('guide-desktop')
  await close()
  await page.reload({ waitUntil: 'networkidle0' })
  await click('.sf-recent > summary')
  await click('.sf-recent button')
  await click('.sf-guide-button')
  assert.equal(await page.$eval('.sf-reflection textarea', el => el.value), 'Free does not remove the cost of time.')
  assert.equal(await page.$eval('.sf-saved-list textarea', el => el.value), 'Ask potential participants about workload.')
  assert.equal(await page.$$eval('.sf-saved-list article', els => els.length), 2)
  await close()
  await click('.sf-trail-button')
  assert.equal(await page.$$eval('.sf-trail-list li', els => els.length), 2)
  await click('.sf-trail-list button')
  assert.equal((await readFind()).id, first.id)
  await close()
  await click('.sf-export-button')
  await page.evaluate(() => { window.print = () => {} })
  await click('.sf-export-options > button:last-child')
  await page.waitForSelector('.sf-print')
  assert.equal(await page.$$eval('.sf-print article', els => els.length), sample.cards.length)
  await page.emulateMediaType('print')
  await page.pdf({ path: path.join(output, 'safari-print.pdf'), format: 'A4', printBackground: false, preferCSSPageSize: true })
  await page.emulateMediaType('screen')
  await page.evaluate(() => window.dispatchEvent(new Event('afterprint')))
  const downloaded = (await fs.readdir(path.join(output, 'downloads'))).filter(name => name.endsWith('.md'))
  assert.ok(downloaded.length)
  const downloadedText = await fs.readFile(path.join(output, 'downloads', downloaded.at(-1)), 'utf8')
  assert.ok(downloadedText.includes('Ask potential participants about workload.'))
  checks.push('Six coloured piles and static doodles; digestible finding reveals; detours; source details; 320–1440px layouts; saved notes and trail after reload; copy; Markdown; complete PDF')
  console.log('Passed discovery, field guide, exports and responsive layouts.')

  checks.push(...await verifySafariReveal(page, sample, { origin, output }))
  assert.equal(runs, 0, 'Browser fixtures must not invoke a paid generation request')
  assert.equal(await page.evaluate(() => localStorage.getItem('safari-test-change-cards-sentinel')), 'untouched')

  if (live) {
    mode = 'live'
    await page.setViewport({ width: 1440, height: 1000 })
    await page.goto(`${origin}/safari/`, { waitUntil: 'networkidle0' })
    await page.type('#sf-challenge', sample.challenge)
    console.log('Starting one live evidence request; this may take 1–2 minutes.')
    await click('.sf-challenge-form .sf-primary')
    await page.waitForSelector('[data-research-busy="false"]', { timeout: 280000 })
    const latest = await page.evaluate(() => { const data = JSON.parse(localStorage.getItem('evidence-safari.field-guides.v1')); return data.safaris.find(s => s.id === data.currentId) })
    assert.ok(latest.cards.length)
    assert.ok(latest.timing)
    assert.ok(!latest.cost.entries?.some(e => /image|illustrat/i.test(e.label || '')))
    await fs.writeFile(path.join(output, 'live-run.json'), JSON.stringify({ id: latest.id, findings: latest.cards.length, cost: latest.cost, timing: latest.timing, cacheHit: latest.cacheHit }, null, 2))
    checks.push(`Live endpoint returned ${latest.cards.length} findings for $${latest.cost.estimatedUsd} estimated, without image generation`)
  }
  await page.goto(origin, { waitUntil: 'networkidle0' })
  await page.waitForSelector('.entry-page')
  assert.ok((await page.$eval('body', el => el.innerText)).includes('Push an idea'))
  await page.setViewport({ width: 390, height: 844 }); await noOverflow()
  assert.equal(await page.$('.sf-app'), null)
  checks.push('Change Cards still loads independently on desktop and mobile')
  assert.deepEqual(errors, [])
  await fs.writeFile(path.join(output, 'verification.json'), JSON.stringify({ passed: true, live, checks, runtimeErrors: errors, checkedAt: new Date().toISOString() }, null, 2))
  console.log(JSON.stringify({ passed: true, live, checks, runtimeErrors: errors }, null, 2))
} finally { await browser.close() }
