import { fileURLToPath } from 'node:url'
import assert from 'node:assert/strict'
import { mkdir, readFile } from 'node:fs/promises'
import puppeteer from 'puppeteer-core'

const origin = process.env.VERIFY_ORIGIN || 'http://localhost:8787'
const output = fileURLToPath(new URL('../output/ux-improvements/', import.meta.url))
await mkdir(output, { recursive: true })
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true, args: ['--no-sandbox'] })
const page = await browser.newPage()
page.setDefaultTimeout(12000)
const errors = []
let failSparks = false
page.on('pageerror', (error) => errors.push(error.message))
await page.setRequestInterception(true)
page.on('request', (request) => {
  if (!request.url().includes('/api/sparks')) return request.continue()
  return request.respond({ status: failSparks ? 503 : 200, contentType: 'application/json', body: JSON.stringify(failSparks ? { error: 'Test failure' } : { sparks: ['A doorstep book exchange', 'A neighbour hosts tea', 'A shared story trolley'] }) })
})
const settle = () => new Promise((resolve) => setTimeout(resolve, 1100))
const readSession = () => page.evaluate(() => JSON.parse(localStorage.getItem('change-cards-session-v1')))
const screenshot = async (name) => { await settle(); await page.screenshot({ path: `${output}${name}.png`, fullPage: true }) }
const setText = async (selector, text) => {
  await page.focus(selector)
  await page.keyboard.down('Meta'); await page.keyboard.press('KeyA'); await page.keyboard.up('Meta')
  await page.keyboard.type(text)
}
const openCard = async (id) => {
  await page.click(`.tabletop-canvas [data-card-id="${id}"] .card-front`)
  await page.waitForSelector('.response-editor')
  await settle()
}
const noOverflow = async () => {
  const overflow = await page.evaluate(() => ({width:innerWidth,scroll:document.documentElement.scrollWidth, elements:[...document.querySelectorAll('body *')].map(e=>{const r=e.getBoundingClientRect(),c=getComputedStyle(e);return {class:e.className, left:r.left,right:r.right,width:c.width,height:c.height,transform:c.transform,animation:c.animation,minWidth:c.minWidth}}).filter(e=>e.right>innerWidth+1||e.left < -1).slice(0,12)}))
  assert.ok(overflow.scroll <= overflow.width + 1, `Document has horizontal overflow: ${JSON.stringify(overflow)}`)
}

try {
  await browser.defaultBrowserContext().overridePermissions(origin, ['clipboard-read', 'clipboard-write'])
  const cdp = await page.createCDPSession()
  await cdp.send('Browser.setDownloadBehavior', { behavior: 'allow', downloadPath: output })
  await page.setViewport({ width: 1440, height: 900 })
  await page.goto(origin, { waitUntil: 'networkidle0' })
  await screenshot('01-entry-desktop')
  for (const [width, height] of [[390, 844], [320, 568], [720, 900]]) {
    await page.setViewport({ width, height })
    await noOverflow()
    assert.equal(await page.$eval('.idea-form > .ink-button', (button) => button.getBoundingClientRect().bottom <= innerHeight), true, `Start button below viewport at ${width}px`)
    await screenshot(`entry-${width}`)
  }
  await page.setViewport({ width: 1440, height: 900 })
  await page.click('.try-example')
  assert.ok(await page.$eval('#idea', (element) => element.value.length > 0))
  await page.click('.idea-form > .ink-button')
  await page.waitForSelector('.tabletop')
  const originalIdea = (await readSession()).idea
  await screenshot('04-table-desktop')
  await page.setViewport({ width: 390, height: 844 })
  await screenshot('05-table-mobile')
  assert.equal(await page.evaluate(() => document.querySelector('.mobile-idea-summary').getBoundingClientRect().bottom < document.querySelector('.side-deck').getBoundingClientRect().top), true, 'Mobile idea overlaps the bottom dock')
  await page.click('.draw-card-button')
  await page.waitForSelector('.table-card-shell:not(.deal-flight-card)')
  await settle()
  const cardId = (await readSession()).dealtCardIds[0]
  await openCard(cardId)
  await screenshot('06-editor-mobile')
  await page.setViewport({ width: 1440, height: 900 })
  await screenshot('07-editor-desktop')
  assert.ok(await page.$eval('.generation-surface', (element) => element.getBoundingClientRect().height > 300), 'Editor collapses after resizing')
  const draft = 'A weekly doorstep book exchange, hosted by neighbours with tea.'
  await setText('.response-editor', draft)
  await page.click('.surface-close')
  await page.waitForSelector('.response-editor', { hidden: true })
  await openCard(cardId)
  assert.equal(await page.$eval('.response-editor', (element) => element.value), draft)
  await page.keyboard.press('Escape')
  await page.waitForSelector('.response-editor', { hidden: true })
  await page.reload({ waitUntil: 'networkidle0' })
  await openCard(cardId)
  assert.equal(await page.$eval('.response-editor', (element) => element.value), draft, 'Draft lost on reload')
  await page.click('.active-card-scrim', { offset: { x: 10, y: 100 } })
  await page.waitForSelector('.response-editor', { hidden: true })
  await openCard(cardId)
  assert.equal(await page.$eval('.response-editor', (element) => element.value), draft, 'Draft lost on backdrop dismissal')
  await page.click('.response-submit')
  await page.waitForSelector('.saved-pins')
  assert.equal((await readSession()).swarm[cardId].note, draft)
  assert.equal((await readSession()).drafts[cardId], undefined)
  await page.click('.logo-button')
  await page.waitForSelector('.resume-session')
  assert.equal((await readSession()).swarm[cardId].note, draft, 'Home deleted a saved idea')
  await screenshot('08-resume')
  await page.click('.resume-session .text-button')
  await page.waitForSelector('dialog[open]')
  await screenshot('09-reset')
  await page.keyboard.press('Escape')
  assert.equal((await readSession()).swarm[cardId].note, draft)
  await page.click('.resume-session .ink-button')
  await page.waitForSelector('.tabletop')
  await page.click('.deal-all-button')
  await page.waitForSelector('.is-arranged')
  assert.equal(await page.$$eval('.tabletop-canvas > .table-card-shell', (cards) => cards.length), 40)
  await screenshot('10-arranged-desktop')
  assert.equal(await page.$('.browse-heading,.table-view-controls'), null)
  for (const width of [1024, 720, 390, 320]) {
    await page.setViewport({ width, height: 844 })
    await settle()
    await noOverflow()
    await screenshot(`canvas-${width}`)
  }
  await page.setViewport({ width: 1440, height: 900 })
  await page.click('.routes-button')
  await page.waitForSelector('.route-chooser')
  await screenshot('12-routes-desktop')
  await page.setViewport({ width: 390, height: 844 })
  await screenshot('13-routes-mobile')
  await page.click('.route-slip')
  await page.waitForSelector('.has-active-route')
  await settle()
  await screenshot('14-route-mobile')
  assert.equal(await page.$eval('.route-ribbon', (element) => getComputedStyle(element).display !== 'none' && element.innerText.includes('From assumption to evidence')), true)
  await page.setViewport({ width: 1440, height: 900 })
  await screenshot('15-route-desktop')
  for (const id of [13, 7, 14, 15]) {
    if ((await readSession()).swarm[id]?.visited) continue
    await openCard(id)
    await setText('.response-editor', `An experiment for route step ${id}.`)
    await page.click('.response-submit')
    await page.waitForSelector('.response-editor', { hidden: true })
  }
  await new Promise((resolve) => setTimeout(resolve, 2000))
  assert.equal((await readSession()).activeRouteId, 'assumption-to-evidence', 'Completed route vanished')
  assert.ok(await page.$eval('.route-ribbon', (element) => element.innerText.includes('complete')))
  await screenshot('route-complete')
  await page.click('.route-ribbon > button')
  await page.waitForSelector('.has-active-route', { hidden: true })
  await page.setViewport({ width: 390, height: 844 })
  await page.click('.scrapbook-nav-button')
  await page.waitForSelector('.scrapbook-layer')
  await screenshot('scrapbook-mobile')
  await page.click('.scrapbook-copy-all')
  assert.ok((await page.evaluate(() => navigator.clipboard.readText())).includes(draft))
  await page.click('.scrapbook-close')
  await page.click('.new-idea-button')
  await page.waitForSelector('dialog[open]')
  await page.click('.export-session-button')
  await settle()
  const exported = await readFile(`${output}change-cards-ideas.txt`, 'utf8')
  assert.ok(exported.includes(originalIdea) && exported.includes(draft))
  await page.click('.reset-session-actions .ink-button')
  await page.waitForSelector('#idea')
  assert.equal(await page.$eval('#idea', (element) => element.value), '')
  assert.deepEqual((await readSession()).swarm, {})
  await page.click('.entry-mode-toggle button:last-child')
  await page.click('.coop-entry-choices button:last-child')
  assert.equal(await page.$('#idea'), null, 'Joining still asks for idea first')
  await screenshot('coop-join-mobile')
  await page.click('.coop-entry-choices button:first-child')
  assert.ok(await page.$('#idea'))
  await screenshot('coop-host-mobile')
  // AI failure never blocks writing, and retry recovers in the same card.
  await page.click('.entry-mode-toggle button:first-child')
  await page.click('.try-example')
  await page.click('.idea-form > .ink-button')
  failSparks = true
  await page.click('.draw-card-button')
  await settle()
  const failedCard = (await readSession()).dealtCardIds[0]
  await openCard(failedCard)
  await page.waitForSelector('.spark-retry')
  await setText('.response-editor', 'Writing continues without AI.')
  assert.equal(await page.$eval('.response-submit', (button) => button.disabled), false)
  failSparks = false
  await page.click('.spark-retry')
  await page.waitForSelector('.editor-spark [data-spark]')
  await page.mouse.move(0, 0)
  await page.focus('.response-editor')
  const spark = await page.$eval('.editor-spark [data-spark]', (button) => button.dataset.spark)
  await new Promise((resolve) => setTimeout(resolve, 6500))
  assert.notEqual(await page.$eval('.editor-spark [data-spark]', (button) => button.dataset.spark), spark, 'Restored sparks did not rotate')
  assert.equal(await page.$('.another-spark,.spark-help-label,.editor-card-title'), null)
  await page.emulateMediaFeatures([{ name: 'prefers-reduced-motion', value: 'reduce' }])
  await noOverflow()
  assert.deepEqual(errors, [])
  console.log('UX verified: responsive entry and canvas, draft recovery, safe home/reset/export, saved-idea copying, four-step route completion, co-op entry, AI failure/retry and rotating sparks. No page errors.')
} catch (error) {
  await page.screenshot({ path: `${output}verification-failure.png`, fullPage: true })
  console.error('Page errors:', errors)
  throw error
} finally {
  await browser.close()
}
